# Generated by Django 4.1.7 on 2023-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='audio_file',
            field=models.FileField(upload_to='static/audio/'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcription',
            field=models.TextField(max_length=1000),
        ),
    ]
