# Generated by Django 4.1.7 on 2023-07-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectP', '0002_alter_transcription_audio_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transcription',
        ),
    ]
